# =============================================================================
# Biomass Production Utility — Capacity & Condition (PCA-Weighted)
# =============================================================================
# Computes the overall soil capacity and condition for biomass production
# using PCA-derived weights from 11_3b_pca_weights.R, following the method
# of Evangelista et al. (2025) Soil Advances 4:100080:
#
#   Capacity  = Σ(Wi × U_i)     where Wi = PCA weight for indicator i
#   Condition = Σ(Wi × U*_i)    (same weights applied to condition utilities)
#
# If PCA weights are not available, falls back to equal weights (1/n).
#
# Inputs: individual utility rasters from 11_3_soil_utility_map.R
#         PCA weights CSV from 11_3b_pca_weights.R
# Outputs: overall capacity raster, condition raster, change raster
# Plots are generated by 11_3b2_biomass_production_plots.R
#
# Reference:
#   Evangelista et al. (2025) Soil Advances 4:100080
#   Hunakunti et al. (2025) Int. Soil & Water Conservation Research 13:771–794
#   Francos et al. (2025) Catena 259:109372
# =============================================================================

# --- Packages ----------------------------------------------------------------
suppressPackageStartupMessages({
  library(terra)
})

set.seed(42)

# --- Terra options -----------------------------------------------------------
temp_dir <- file.path(getwd(), "temp_terra")
dir.create(temp_dir, showWarnings = FALSE, recursive = TRUE)
terraOptions(memfrac = 0.5, tempdir = temp_dir)

# =============================================================================
# CONFIGURATION
# =============================================================================
depth_layer <- "X0.30cm"

# Individual utility raster paths (generated by 11_3_soil_utility_map.R)
utility_base <- file.path("Data", "data_out")

raster_paths <- list(
  capacity = list(
    pH   = file.path(utility_base, "pH_utility",
                     paste0("pH_capacity_utility_", depth_layer, ".tif")),
    BD   = file.path(utility_base, "Bulk_Density_utility",
                     paste0("Bulk_Density_capacity_utility_", depth_layer, ".tif")),
    AWC  = file.path(utility_base, "AWC_utility",
                     paste0("AWC_capacity_utility_", depth_layer, ".tif"))
  ),
  condition = list(
    pH   = file.path(utility_base, "pH_utility",
                     paste0("pH_condition_utility_", depth_layer, ".tif")),
    BD   = file.path(utility_base, "Bulk_Density_utility",
                     paste0("Bulk_Density_condition_utility_", depth_layer, ".tif")),
    AWC  = file.path(utility_base, "AWC_utility",
                     paste0("AWC_condition_utility_", depth_layer, ".tif"))
  )
)

# Output directory
output_base <- file.path(utility_base, "Biomass_production_utility")
dir.create(output_base, showWarnings = FALSE, recursive = TRUE)

# =============================================================================
# Load PCA weights (from 11_3b_pca_weights.R)
# =============================================================================
pca_weights_csv <- file.path(output_base, "PCA",
                             paste0("pca_weights_simple_", depth_layer, ".csv"))

# Mapping from PCA indicator names to raster list names
indicator_to_raster <- c(U_pH = "pH", U_BD = "BD", U_AWC = "AWC")

if (file.exists(pca_weights_csv)) {
  pca_wt <- read.csv(pca_weights_csv, stringsAsFactors = FALSE)
  cat("  PCA weights loaded from: ", pca_weights_csv, "\n", sep = "")
  cat("  Weights:\n")
  for (i in seq_len(nrow(pca_wt))) {
    cat("    ", pca_wt$indicator[i], " = ", round(pca_wt$weight[i], 4), "\n", sep = "")
  }
  use_pca_weights <- TRUE
} else {
  cat("  ** PCA weights not found: ", pca_weights_csv, "\n", sep = "")
  cat("  ** Falling back to equal weights (1/3)\n", sep = "")
  cat("  ** Run 11_3b_pca_weights.R first for PCA-based weights\n", sep = "")
  use_pca_weights <- FALSE
}
cat("\n")

# =============================================================================
# Verify inputs exist
# =============================================================================
cat("Checking input rasters...\n")
all_paths <- unlist(raster_paths)
missing <- all_paths[!file.exists(all_paths)]
if (length(missing) > 0) {
  cat("MISSING rasters:\n")
  cat(paste0("  ", missing, "\n"))
  stop("Run 11_3_soil_utility_map.R for each property/mode first.")
}
cat("  All 6 rasters found.\n\n")


# =============================================================================
# PART 1: Load and average utility rasters
# =============================================================================
cat(paste(rep("=", 70), collapse = ""), "\n")
cat("PART 1: Computing overall capacity and condition\n")
cat(paste(rep("=", 70), collapse = ""), "\n\n")

load_and_summarise <- function(paths, label) {
  cat("  Loading ", label, " rasters...\n", sep = "")
  rasters <- lapply(paths, rast)

  # Print individual stats (disk-based, no values())
  for (nm in names(rasters)) {
    r  <- rasters[[nm]]
    s1 <- global(r, fun = "min",  na.rm = TRUE)$min
    s2 <- global(r, fun = "max",  na.rm = TRUE)$max
    s3 <- global(r, fun = "mean", na.rm = TRUE)$mean
    nc <- global(r, fun = "notNA")$notNA
    cat(sprintf("    %s: min=%.3f  mean=%.3f  max=%.3f  (n=%s)\n",
                nm, s1, s3, s2, format(nc, big.mark = ",")))
  }

  if (use_pca_weights) {
    # PCA-weighted sum: Score = Σ(Wi × Ui)
    cat("  Computing PCA-weighted sum...\n")

    # Build weighted raster: sum of (weight_i * raster_i) for selected indicators
    weighted_rast <- NULL
    total_weight_used <- 0

    for (i in seq_len(nrow(pca_wt))) {
      ind_name    <- pca_wt$indicator[i]
      ind_weight  <- pca_wt$weight[i]
      raster_name <- indicator_to_raster[ind_name]

      if (!is.na(raster_name) && raster_name %in% names(rasters)) {
        cat(sprintf("    %s: weight=%.4f\n", ind_name, ind_weight))
        if (is.null(weighted_rast)) {
          weighted_rast <- rasters[[raster_name]] * ind_weight
        } else {
          weighted_rast <- weighted_rast + rasters[[raster_name]] * ind_weight
        }
        total_weight_used <- total_weight_used + ind_weight
      } else {
        cat("    ** ", ind_name, ": raster not found, skipping\n", sep = "")
      }
    }

    if (is.null(weighted_rast)) {
      cat("  ** No matching rasters for PCA weights — falling back to equal mean\n")
      stack <- rast(rasters)
      result_rast <- app(stack, fun = function(x) mean(x, na.rm = TRUE))
    } else {
      result_rast <- weighted_rast
      cat(sprintf("    Total weight used: %.4f\n", total_weight_used))
    }
  } else {
    # Fallback: equal-weight average (U_pH + U_BD + U_AWC) / 3
    cat("  Computing equal-weight mean (n=", length(rasters), ")...\n", sep = "")
    stack <- rast(rasters)
    result_rast <- app(stack, fun = function(x) mean(x, na.rm = TRUE))
  }

  s1 <- global(result_rast, fun = "min",  na.rm = TRUE)$min
  s2 <- global(result_rast, fun = "max",  na.rm = TRUE)$max
  s3 <- global(result_rast, fun = "mean", na.rm = TRUE)$mean
  cat(sprintf("  %s: min=%.3f  mean=%.3f  max=%.3f\n\n",
              label, s1, s3, s2))

  return(result_rast)
}

capacity_rast  <- load_and_summarise(raster_paths$capacity,  "Capacity")
condition_rast <- load_and_summarise(raster_paths$condition, "Condition")

# Save overall rasters
cap_tif <- file.path(output_base,
                     paste0("biomass_overall_capacity_", depth_layer, ".tif"))
con_tif <- file.path(output_base,
                     paste0("biomass_overall_condition_", depth_layer, ".tif"))
writeRaster(capacity_rast,  cap_tif, overwrite = TRUE)
writeRaster(condition_rast, con_tif, overwrite = TRUE)
cat("  Saved: ", cap_tif, "\n", sep = "")
cat("  Saved: ", con_tif, "\n\n", sep = "")

# =============================================================================
# PART 2: Biomass Production Change — mean(U_geno − U_pheno)
# =============================================================================
# Direct measure of change: ΔU = U_geno − U_pheno per property
#   ΔU < 0 → phenosoil utility higher → Improved
#   ΔU ≈ 0 → no change
#   ΔU > 0 → genosoil utility higher → Degraded
# Averaged across pH, BD, AWC for overall biomass production change
# =============================================================================
cat("Computing biomass production change (mean \u0394U)...\n")

# Capacity functions (same as 11_3_soil_utility_map.R)
cap_fns <- list(
  pH  = function(x) exp(-(x - 6.5)^2 / 2),
  BD  = function(x) 1 / (1 + exp(10 * (x - 1.5))),
  AWC = function(x) 1 / (1 + exp(-1.0 * (x - 12)))
)

input_base <- file.path("Data", "data_out", "pedogenon_zonal_means")
delta_u_list <- list()

for (prop in c("pH", "BD", "AWC")) {
  prop_full <- switch(prop, pH = "pH", BD = "Bulk_Density", AWC = "AWC")
  geno_path  <- file.path(input_base, "Geno",
                           paste0(prop_full, "_geno_pedogenon_mean_",
                                  depth_layer, ".tif"))
  pheno_path <- file.path(input_base, "Pheno",
                           paste0(prop_full, "_pheno_pedogenon_mean_",
                                  depth_layer, ".tif"))

  cat("  ", prop, ": loading geno + pheno rasters...\n", sep = "")
  geno_r  <- rast(geno_path)
  pheno_r <- rast(pheno_path)

  fn <- cap_fns[[prop]]
  u_geno  <- app(geno_r,  fun = function(x) fn(x))
  u_pheno <- app(pheno_r, fun = function(x) fn(x))
  delta_u_list[[prop]] <- u_geno - u_pheno

  d_min  <- global(delta_u_list[[prop]], fun = "min",  na.rm = TRUE)$min
  d_max  <- global(delta_u_list[[prop]], fun = "max",  na.rm = TRUE)$max
  d_mean <- global(delta_u_list[[prop]], fun = "mean", na.rm = TRUE)$mean
  cat(sprintf("    \u0394U: min=%.3f  mean=%.3f  max=%.3f\n",
              d_min, d_mean, d_max))
}

# Mean ΔU across all properties (PCA-weighted if available)
if (use_pca_weights) {
  cat("  Computing PCA-weighted \u0394U across properties...\n")
  delta_stack <- rast(delta_u_list)

  # Build weight vector matching delta_u_list order
  delta_weights <- sapply(names(delta_u_list), function(prop) {
    ind_name <- paste0("U_", prop)
    idx <- match(ind_name, pca_wt$indicator)
    if (!is.na(idx)) pca_wt$weight[idx] else 0
  })
  # Renormalise in case some indicators were dropped by PCA
  if (sum(delta_weights) > 0) {
    delta_weights <- delta_weights / sum(delta_weights)
  } else {
    delta_weights <- rep(1 / length(delta_u_list), length(delta_u_list))
  }
  cat("    Weights: ", paste(names(delta_weights), round(delta_weights, 4),
                              sep = "=", collapse = ", "), "\n", sep = "")
  change_rast <- app(delta_stack, fun = function(x) sum(x * delta_weights, na.rm = TRUE))
} else {
  cat("  Averaging \u0394U across properties (equal weights)...\n")
  delta_stack <- rast(delta_u_list)
  change_rast <- app(delta_stack, fun = function(x) mean(x, na.rm = TRUE))
}

change_tif <- file.path(output_base,
                        paste0("biomass_change_", depth_layer, ".tif"))
writeRaster(change_rast, change_tif, overwrite = TRUE)

chg_s1 <- global(change_rast, fun = "min",  na.rm = TRUE)$min
chg_s2 <- global(change_rast, fun = "max",  na.rm = TRUE)$max
chg_s3 <- global(change_rast, fun = "mean", na.rm = TRUE)$mean
cat(sprintf("  Change: min=%.4f  mean=%.4f  max=%.4f\n\n",
            chg_s1, chg_s3, chg_s2))

# =============================================================================
# Summary
# =============================================================================
cat(paste(rep("=", 70), collapse = ""), "\n")
cat("DONE — Rasters saved to: ", output_base, "\n")
if (use_pca_weights) {
  cat("  Weighting: PCA-derived (Evangelista et al. 2025)\n")
  cat("  Weights source: ", pca_weights_csv, "\n")
} else {
  cat("  Weighting: Equal (1/n fallback)\n")
}
cat(paste(rep("=", 70), collapse = ""), "\n")
cat("  ", cap_tif, "\n")
cat("  ", con_tif, "\n")
cat("  ", change_tif, "\n")
cat("\nNext: source('R/11_3b2_biomass_production_plots.R') for maps & graphs\n")
cat(paste(rep("=", 70), collapse = ""), "\n")
