# =============================================================================
# PCA-Based Indicator Selection & Weights for Biomass Production Utility
# =============================================================================
# Performs Principal Component Analysis on soil property utility values to
# derive data-driven weights for aggregating individual utilities into an
# overall biomass production capacity/condition score.
#
# Method: Evangelista et al. (2025) Soil Advances 4:100080, following the
#         PCA approach of Ng et al. (2024a) / Andrews & Carroll (2001):
#
#   1. Run PCA on utility values (center=TRUE, scale.=FALSE)
#   2. Retain PCs with eigenvalue >= 1 (Kaiser); if < 3, include PCs >= 5%
#   3. Assign each indicator to the retained PC where it has highest |loading|
#      (ALL indicators retained — no elimination step)
#   4. Weights = % variance of indicator's PC / total retained variance
#   5. Normalise weights to sum to 1
#
# Final score (Eq. 1):  Score = Sum( Wi * Ui )
#
# Inputs:
#   - Individual capacity utility rasters from 11_3_soil_utility_map.R
#     (pH, Bulk_Density, AWC)
#
# Outputs:
#   - PCA weights CSV (pca_weights.csv)
#   - PCA diagnostics CSV (eigenvalues, loadings)
#   - Publication-quality plots: scree plot, variable contribution, biplot
#
# Run this BEFORE 11_3b_biomass_production_utility.R
#
# Reference:
#   Evangelista et al. (2025) Soil Advances 4:100080
#   Ng et al. (2024a) — PCA flowchart for indicator selection
#   Andrews & Carroll (2001); Andrews et al. (2002, 2004)
# =============================================================================

# --- Packages ----------------------------------------------------------------
suppressPackageStartupMessages({
  library(terra)
  library(ggplot2)
  library(corrplot)
})

set.seed(42)

# --- Terra options -----------------------------------------------------------
temp_dir <- file.path(getwd(), "temp_terra")
dir.create(temp_dir, showWarnings = FALSE, recursive = TRUE)
terraOptions(memfrac = 0.5, tempdir = temp_dir)

# =============================================================================
# CONFIGURATION
# =============================================================================
depth_layer   <- "X0.30cm"
sample_size   <- 50000L       # random pixels for PCA (memory-efficient)

utility_base <- file.path("Data", "data_out")
output_base  <- file.path(utility_base, "Biomass_production_utility", "PCA")
dir.create(output_base, showWarnings = FALSE, recursive = TRUE)

# Capacity utility rasters (generated by 11_3_soil_utility_map.R)
cap_paths <- list(
  U_pH  = file.path(utility_base, "pH_utility",
                     paste0("pH_capacity_utility_", depth_layer, ".tif")),
  U_BD  = file.path(utility_base, "Bulk_Density_utility",
                     paste0("Bulk_Density_capacity_utility_", depth_layer, ".tif")),
  U_AWC = file.path(utility_base, "AWC_utility",
                     paste0("AWC_capacity_utility_", depth_layer, ".tif"))
)

# Publication theme
theme_pub <- theme_bw(base_size = 12) +
  theme(
    plot.title       = element_text(face = "bold", size = 13, hjust = 0.5),
    plot.subtitle    = element_text(size = 10, hjust = 0.5, colour = "grey30"),
    axis.title       = element_text(size = 11),
    axis.text        = element_text(size = 9),
    legend.title     = element_text(face = "bold", size = 10),
    legend.text      = element_text(size = 9),
    panel.grid.minor = element_blank(),
    plot.margin      = margin(10, 10, 10, 10)
  )

# =============================================================================
# 1. Verify inputs and load rasters
# =============================================================================
cat(paste(rep("=", 70), collapse = ""), "\n")
cat("PCA-Based Indicator Weights for Biomass Production Utility\n")
cat(paste(rep("=", 70), collapse = ""), "\n\n")

cat("Checking input rasters...\n")
missing <- names(cap_paths)[!sapply(cap_paths, file.exists)]
if (length(missing) > 0) {
  cat("MISSING rasters:\n")
  cat(paste0("  ", missing, ": ", cap_paths[missing], "\n"))
  stop("Run 11_3_soil_utility_map.R for each property in capacity mode first.")
}
cat("  All", length(cap_paths), "capacity utility rasters found.\n\n")

rasters <- lapply(cap_paths, rast)

# =============================================================================
# 2. Sample utility values for PCA
# =============================================================================
cat("Sampling ", format(sample_size, big.mark = ","),
    " random pixels for PCA...\n", sep = "")

stack <- rast(rasters)
names(stack) <- names(cap_paths)

total_cells <- ncell(stack)
notna_count <- global(stack[[1]], fun = "notNA")$notNA
cat("  Total raster cells : ", format(total_cells, big.mark = ","), "\n", sep = "")
cat("  Non-NA cells       : ", format(notna_count, big.mark = ","), "\n", sep = "")

# Sample random cells — spatSample extracts from all layers at once
n_sample <- min(sample_size, notna_count)
sampled <- spatSample(stack, size = n_sample, method = "random",
                      na.rm = TRUE, as.df = TRUE)

cat("  Sampled pixels     : ", format(nrow(sampled), big.mark = ","), "\n", sep = "")
cat("  Columns            : ", paste(colnames(sampled), collapse = ", "), "\n\n", sep = "")

# Quick summary of sampled data
cat("  Sample summary:\n")
for (col in colnames(sampled)) {
  vals <- sampled[[col]]
  cat(sprintf("    %s: min=%.4f  mean=%.4f  max=%.4f  sd=%.4f\n",
              col, min(vals), mean(vals), max(vals), sd(vals)))
}
cat("\n")

# =============================================================================
# 3. Explore correlation structure
# =============================================================================
cat("Step 1: Correlation matrix of utility values\n")
cor_mat <- cor(sampled, use = "complete.obs")
print(round(cor_mat, 4))
cat("\n")

# Save correlation plot
corr_png <- file.path(output_base, paste0("pca_correlation_matrix_", depth_layer, ".png"))
png(corr_png, width = 6, height = 5, units = "in", res = 300)
corrplot(cor_mat, method = "color", type = "upper", addCoef.col = "black",
         tl.col = "black", tl.srt = 45, number.cex = 1.0,
         title = "Correlation Matrix of Utility Values",
         mar = c(0, 0, 2, 0))
dev.off()
cat("  Saved: ", corr_png, "\n\n", sep = "")

# =============================================================================
# 4. Run PCA (Evangelista et al. 2025 — Step 1)
# =============================================================================
cat("Step 2: Running PCA (center=TRUE, scale.=FALSE)\n")
cat("  scale.=FALSE because utility values are already standardised (0-1)\n\n")

pca_result <- prcomp(sampled, center = TRUE, scale. = FALSE)

# Eigenvalues and variance explained (base R — replaces factoextra::get_eig)
sdev2 <- pca_result$sdev^2
eig_df <- data.frame(
  eigenvalue              = sdev2,
  variance.percent        = 100 * sdev2 / sum(sdev2),
  cumulative.variance.percent = cumsum(100 * sdev2 / sum(sdev2)),
  row.names               = paste0("PC", seq_along(sdev2))
)
cat("  Eigenvalues and variance explained:\n")
print(round(eig_df, 4))
cat("\n")

# Save eigenvalue table
eig_csv <- file.path(output_base, paste0("pca_eigenvalues_", depth_layer, ".csv"))
write.csv(round(eig_df, 6), eig_csv, row.names = TRUE)
cat("  Saved: ", eig_csv, "\n\n", sep = "")

# =============================================================================
# 5. Retain PCs — Kaiser criterion + 5% rule (Step 2)
# =============================================================================
cat("Step 3: Retaining principal components\n")
eigenvalues <- eig_df$eigenvalue
var_percent <- eig_df$variance.percent

# Kaiser: eigenvalue >= 1
kaiser_pcs <- which(eigenvalues >= 1)
cat("  Kaiser criterion (eigenvalue >= 1): ",
    ifelse(length(kaiser_pcs) > 0,
           paste("PC", kaiser_pcs, collapse = ", "),
           "NONE"),
    "\n", sep = "")

# If fewer than 3 PCs via Kaiser, add PCs with >= 5% variance
if (length(kaiser_pcs) < 3) {
  pct5_pcs <- which(var_percent >= 5)
  retained_pcs <- sort(unique(c(kaiser_pcs, pct5_pcs)))
  cat("  Fewer than 3 PCs via Kaiser — applying 5% variance rule\n", sep = "")
  cat("  PCs with >= 5% variance: ",
      paste("PC", pct5_pcs, collapse = ", "), "\n", sep = "")
} else {
  retained_pcs <- kaiser_pcs
}

cat("  ** Retained PCs: ", paste("PC", retained_pcs, collapse = ", "), "\n", sep = "")
cat("  Cumulative variance explained: ",
    round(sum(var_percent[retained_pcs]), 2), "%\n\n", sep = "")

# =============================================================================
# 6. Scree plot (publication quality)
# =============================================================================
cat("  Generating scree plot...\n")

scree_df <- data.frame(
  PC = paste0("PC", seq_along(eigenvalues)),
  Eigenvalue = eigenvalues,
  Variance = var_percent,
  Cumulative = eig_df$cumulative.variance.percent,
  Retained = seq_along(eigenvalues) %in% retained_pcs
)
scree_df$PC <- factor(scree_df$PC, levels = scree_df$PC)

p_scree <- ggplot(scree_df, aes(x = PC, y = Variance)) +
  geom_col(aes(fill = Retained), width = 0.6, alpha = 0.85) +
  geom_line(aes(y = Cumulative, group = 1), colour = "#B2182B",
            linewidth = 0.8) +
  geom_point(aes(y = Cumulative), colour = "#B2182B", size = 3) +
  geom_text(aes(label = sprintf("%.1f%%", Variance)),
            vjust = -0.5, size = 3.5) +
  geom_text(aes(y = Cumulative, label = sprintf("%.1f%%", Cumulative)),
            vjust = -0.8, colour = "#B2182B", size = 3) +
  scale_fill_manual(values = c("TRUE" = "#2166AC", "FALSE" = "grey70"),
                    labels = c("TRUE" = "Retained", "FALSE" = "Not retained"),
                    name = NULL) +
  scale_y_continuous(
    name = "Variance Explained (%)",
    sec.axis = sec_axis(~., name = "Cumulative Variance (%)"),
    limits = c(0, 110), expand = c(0, 0)
  ) +
  geom_hline(yintercept = 5, linetype = "dashed", colour = "grey50",
             linewidth = 0.5) +
  annotate("text", x = 0.6, y = 7, label = "5% threshold",
           colour = "grey50", size = 3, hjust = 0) +
  labs(
    title    = "PCA Scree Plot — Utility Values",
    subtitle = paste0("Depth: ", gsub("X", "", depth_layer),
                      " | ", length(retained_pcs), " PCs retained"),
    x = "Principal Component"
  ) +
  theme_pub +
  theme(legend.position = c(0.85, 0.85))

scree_png <- file.path(output_base, paste0("pca_scree_plot_", depth_layer, ".png"))
ggsave(scree_png, p_scree, width = 8, height = 5, dpi = 300)
cat("  Saved: ", scree_png, "\n\n", sep = "")

# =============================================================================
# 7. Loadings analysis — assign ALL indicators to best PC (no selection/dropping)
# =============================================================================
cat("Step 4: Assign all indicators to their highest-loading PC\n")
cat("  (All indicators retained — no 10% threshold elimination)\n\n")

loadings_mat <- pca_result$rotation[, retained_pcs, drop = FALSE]
cat("  Loadings matrix (retained PCs):\n")
print(round(loadings_mat, 4))
cat("\n")

# Save full loadings
loadings_csv <- file.path(output_base, paste0("pca_loadings_", depth_layer, ".csv"))
write.csv(round(pca_result$rotation, 6), loadings_csv, row.names = TRUE)
cat("  Saved: ", loadings_csv, "\n\n", sep = "")

# --- Assign each indicator to the retained PC where it has highest |loading| ---
all_indicators   <- rownames(loadings_mat)
indicator_pc_map <- list()

for (ind in all_indicators) {
  abs_loads <- abs(loadings_mat[ind, ])
  best_pc   <- retained_pcs[which.max(abs_loads)]
  indicator_pc_map[[ind]] <- best_pc
  cat("  ", ind, " -> PC", best_pc,
      " (|loading| = ", round(max(abs_loads), 4), ")\n", sep = "")
}

unique_indicators <- names(indicator_pc_map)
cat("\n  All ", length(unique_indicators), " indicators included: ",
    paste(unique_indicators, collapse = ", "), "\n", sep = "")
cat("  PC assignments:\n")
for (ind in unique_indicators) {
  cat("    ", ind, " -> PC", indicator_pc_map[[ind]], "\n", sep = "")
}

# =============================================================================
# 8. Compute normalised weights (Step 5)
# =============================================================================
cat("\nStep 5: Computing normalised weights\n")

# Weight = variance explained by indicator's PC / total variance of retained PCs
total_retained_var <- sum(var_percent[retained_pcs])
raw_weights <- sapply(unique_indicators, function(ind) {
  pc_idx <- indicator_pc_map[[ind]]
  var_percent[pc_idx]
})

# Normalise to sum to 1
norm_weights <- raw_weights / sum(raw_weights)

cat("  Total retained variance: ", round(total_retained_var, 2), "%\n", sep = "")
cat("\n  PCA-derived weights (normalised to sum to 1):\n")
weight_df <- data.frame(
  Indicator    = unique_indicators,
  PC           = paste0("PC", sapply(unique_indicators, function(i) indicator_pc_map[[i]])),
  PC_Variance  = round(raw_weights, 4),
  Weight       = round(norm_weights, 4),
  stringsAsFactors = FALSE
)
print(weight_df, row.names = FALSE)
cat("  Sum of weights: ", round(sum(norm_weights), 4), "\n\n", sep = "")

# =============================================================================
# 9. Save weights CSV (used by 11_3b_biomass_production_utility.R)
# =============================================================================
weights_csv <- file.path(output_base, paste0("pca_weights_", depth_layer, ".csv"))
write.csv(weight_df, weights_csv, row.names = FALSE)
cat("  Weights CSV saved: ", weights_csv, "\n", sep = "")

# Also save a simple key-value version for easy loading
simple_weights <- data.frame(
  indicator = unique_indicators,
  weight    = norm_weights,
  stringsAsFactors = FALSE
)
simple_csv <- file.path(output_base, paste0("pca_weights_simple_", depth_layer, ".csv"))
write.csv(simple_weights, simple_csv, row.names = FALSE)
cat("  Simple weights CSV: ", simple_csv, "\n\n", sep = "")

# =============================================================================
# 10. Variable contribution plot (publication quality — base R + ggplot2)
# =============================================================================
cat("  Generating variable contribution plot...\n")

# Compute variable contributions (%) per PC
# Contribution = (loading^2 / eigenvalue) * 100
contrib_mat <- sweep(pca_result$rotation^2, 2, sdev2, "/") * 100
contrib_df <- as.data.frame(contrib_mat[, 1:min(2, ncol(contrib_mat))])
contrib_df$Variable <- rownames(contrib_df)
contrib_df$Total_Contrib <- rowSums(contrib_mat[, retained_pcs, drop = FALSE])

# Loading coordinates for arrows (PC1 vs PC2)
load_df <- as.data.frame(pca_result$rotation[, 1:2])
colnames(load_df) <- c("PC1", "PC2")
load_df$Variable <- rownames(load_df)
load_df$Contribution <- contrib_df$Total_Contrib

p_contrib <- ggplot(load_df, aes(x = PC1, y = PC2)) +
  geom_segment(aes(xend = 0, yend = 0, colour = Contribution),
               arrow = arrow(length = unit(0.25, "cm"), ends = "first"),
               linewidth = 1) +
  geom_text(aes(label = Variable, colour = Contribution),
            vjust = -0.8, size = 4, fontface = "bold") +
  geom_hline(yintercept = 0, linetype = "dashed", colour = "grey60") +
  geom_vline(xintercept = 0, linetype = "dashed", colour = "grey60") +
  scale_colour_viridis_c(name = "Contribution (%)") +
  labs(
    title    = "PCA Variable Contributions",
    subtitle = paste0("Depth: ", gsub("X", "", depth_layer)),
    x = paste0("PC1 (", round(var_percent[1], 1), "%)"),
    y = paste0("PC2 (", round(var_percent[2], 1), "%)")
  ) +
  coord_fixed() +
  theme_pub

contrib_png <- file.path(output_base,
                         paste0("pca_variable_contributions_", depth_layer, ".png"))
ggsave(contrib_png, p_contrib, width = 8, height = 6, dpi = 300)
cat("  Saved: ", contrib_png, "\n", sep = "")

# =============================================================================
# 11. Biplot (publication quality — base R + ggplot2)
# =============================================================================
cat("  Generating biplot...\n")

# Scores (individuals) on PC1 vs PC2
scores_df <- as.data.frame(pca_result$x[, 1:2])
colnames(scores_df) <- c("PC1", "PC2")

# Scale loadings to match score range for overlay
score_range <- max(abs(range(scores_df$PC1)), abs(range(scores_df$PC2)))
load_scale  <- score_range * 0.8 / max(abs(pca_result$rotation[, 1:2]))

arrow_df <- as.data.frame(pca_result$rotation[, 1:2] * load_scale)
colnames(arrow_df) <- c("PC1", "PC2")
arrow_df$Variable <- rownames(arrow_df)

p_biplot <- ggplot() +
  geom_point(data = scores_df, aes(x = PC1, y = PC2),
             colour = "grey70", size = 0.8, alpha = 0.3) +
  geom_segment(data = arrow_df,
               aes(x = 0, y = 0, xend = PC1, yend = PC2),
               arrow = arrow(length = unit(0.2, "cm")),
               colour = "#B2182B", linewidth = 0.9) +
  geom_text(data = arrow_df, aes(x = PC1 * 1.12, y = PC2 * 1.12, label = Variable),
            colour = "#B2182B", size = 4, fontface = "bold") +
  geom_hline(yintercept = 0, linetype = "dashed", colour = "grey60") +
  geom_vline(xintercept = 0, linetype = "dashed", colour = "grey60") +
  labs(
    title    = "PCA Biplot \u2014 Utility Values",
    subtitle = paste0("Depth: ", gsub("X", "", depth_layer),
                      " | n = ", format(nrow(sampled), big.mark = ",")),
    x = paste0("PC1 (", round(var_percent[1], 1), "%)"),
    y = paste0("PC2 (", round(var_percent[2], 1), "%)")
  ) +
  theme_pub

biplot_png <- file.path(output_base, paste0("pca_biplot_", depth_layer, ".png"))
ggsave(biplot_png, p_biplot, width = 8, height = 6, dpi = 300)
cat("  Saved: ", biplot_png, "\n", sep = "")

# =============================================================================
# 12. Weights bar chart (publication quality)
# =============================================================================
cat("  Generating weights bar chart...\n")

weight_df$Indicator <- factor(weight_df$Indicator, levels = weight_df$Indicator)

p_weights <- ggplot(weight_df, aes(x = Indicator, y = Weight, fill = PC)) +
  geom_col(width = 0.6, alpha = 0.85) +
  geom_text(aes(label = sprintf("%.3f", Weight)), vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set2", name = "Source PC") +
  scale_y_continuous(limits = c(0, max(norm_weights) * 1.2),
                     expand = c(0, 0)) +
  labs(
    title    = "PCA-Derived Indicator Weights",
    subtitle = paste0("Depth: ", gsub("X", "", depth_layer),
                      " | Normalised to sum = 1"),
    x = "Soil Property Utility",
    y = "Weight"
  ) +
  theme_pub

weights_png <- file.path(output_base,
                         paste0("pca_weights_bar_", depth_layer, ".png"))
ggsave(weights_png, p_weights, width = 7, height = 5, dpi = 300)
cat("  Saved: ", weights_png, "\n\n", sep = "")

# =============================================================================
# Summary
# =============================================================================
cat(paste(rep("=", 70), collapse = ""), "\n")
cat("PCA ANALYSIS COMPLETE\n")
cat(paste(rep("=", 70), collapse = ""), "\n\n")
cat("  Retained PCs       : ", paste("PC", retained_pcs, collapse = ", "), "\n", sep = "")
cat("  Selected indicators: ", paste(unique_indicators, collapse = ", "), "\n", sep = "")
cat("  Weights:\n")
for (i in seq_len(nrow(weight_df))) {
  cat("    ", weight_df$Indicator[i], " = ", weight_df$Weight[i],
      " (from ", weight_df$PC[i], ")\n", sep = "")
}
cat("\n  Outputs in: ", output_base, "\n", sep = "")
cat("    ", weights_csv, "\n", sep = "")
cat("    ", simple_csv, "\n", sep = "")
cat("    ", scree_png, "\n", sep = "")
cat("    ", contrib_png, "\n", sep = "")
cat("    ", biplot_png, "\n", sep = "")
cat("    ", weights_png, "\n", sep = "")

cat("\nNext: source('R/11_3b_biomass_production_utility.R') to use these weights\n")
cat(paste(rep("=", 70), collapse = ""), "\n")
