# =============================================================================
# Biomass Production Utility — Capacity & Condition
# =============================================================================
# Computes the overall soil capacity and condition for biomass production
# by averaging individual property utility scores, following Hunakunti et al.
# (2025) ISWCR framework (Eqs. 6 & 10 adapted for biomass indicators):
#
#   Capacity  = (U_pH + U_BD + U_AWC) / 3          [Eq. 6 analog]
#   Condition = (U*_pH + U*_BD + U*_AWC) / 3       [Eq. 10 analog]
#
# Inputs: individual utility rasters from 11_3_soil_utility_map.R
# Outputs: overall capacity raster, condition raster, change raster
# Plots are generated by 11_3b2_biomass_production_plots.R
#
# Reference:
#   Hunakunti et al. (2025) Int. Soil & Water Conservation Research 13:771–794
#   Francos et al. (2025) Catena 259:109372
# =============================================================================

# --- Packages ----------------------------------------------------------------
suppressPackageStartupMessages({
  library(terra)
})

set.seed(42)

# --- Terra options -----------------------------------------------------------
temp_dir <- file.path(getwd(), "temp_terra")
dir.create(temp_dir, showWarnings = FALSE, recursive = TRUE)
terraOptions(memfrac = 0.5, tempdir = temp_dir)

# =============================================================================
# CONFIGURATION
# =============================================================================
depth_layer <- "X0.30cm"

# Individual utility raster paths (generated by 11_3_soil_utility_map.R)
utility_base <- file.path("Data", "data_out")

raster_paths <- list(
  capacity = list(
    pH   = file.path(utility_base, "pH_utility",
                     paste0("pH_capacity_utility_", depth_layer, ".tif")),
    BD   = file.path(utility_base, "Bulk_Density_utility",
                     paste0("Bulk_Density_capacity_utility_", depth_layer, ".tif")),
    AWC  = file.path(utility_base, "AWC_utility",
                     paste0("AWC_capacity_utility_", depth_layer, ".tif"))
  ),
  condition = list(
    pH   = file.path(utility_base, "pH_utility",
                     paste0("pH_condition_utility_", depth_layer, ".tif")),
    BD   = file.path(utility_base, "Bulk_Density_utility",
                     paste0("Bulk_Density_condition_utility_", depth_layer, ".tif")),
    AWC  = file.path(utility_base, "AWC_utility",
                     paste0("AWC_condition_utility_", depth_layer, ".tif"))
  )
)

# Output directory
output_base <- file.path(utility_base, "Biomass_production_utility")
dir.create(output_base, showWarnings = FALSE, recursive = TRUE)

# =============================================================================
# Verify inputs exist
# =============================================================================
cat("Checking input rasters...\n")
all_paths <- unlist(raster_paths)
missing <- all_paths[!file.exists(all_paths)]
if (length(missing) > 0) {
  cat("MISSING rasters:\n")
  cat(paste0("  ", missing, "\n"))
  stop("Run 11_3_soil_utility_map.R for each property/mode first.")
}
cat("  All 6 rasters found.\n\n")


# =============================================================================
# PART 1: Load and average utility rasters
# =============================================================================
cat(paste(rep("=", 70), collapse = ""), "\n")
cat("PART 1: Computing overall capacity and condition\n")
cat(paste(rep("=", 70), collapse = ""), "\n\n")

load_and_summarise <- function(paths, label) {
  cat("  Loading ", label, " rasters...\n", sep = "")
  rasters <- lapply(paths, rast)

  # Print individual stats (disk-based, no values())
  for (nm in names(rasters)) {
    r  <- rasters[[nm]]
    s1 <- global(r, fun = "min",  na.rm = TRUE)$min
    s2 <- global(r, fun = "max",  na.rm = TRUE)$max
    s3 <- global(r, fun = "mean", na.rm = TRUE)$mean
    nc <- global(r, fun = "notNA")$notNA
    cat(sprintf("    %s: min=%.3f  mean=%.3f  max=%.3f  (n=%s)\n",
                nm, s1, s3, s2, format(nc, big.mark = ",")))
  }

  # Average: (U_pH + U_BD + U_AWC) / 3
  cat("  Computing mean (n=", length(rasters), ")...\n", sep = "")
  stack <- rast(rasters)
  avg_rast <- app(stack, fun = function(x) mean(x, na.rm = TRUE))

  s1 <- global(avg_rast, fun = "min",  na.rm = TRUE)$min
  s2 <- global(avg_rast, fun = "max",  na.rm = TRUE)$max
  s3 <- global(avg_rast, fun = "mean", na.rm = TRUE)$mean
  cat(sprintf("  %s: min=%.3f  mean=%.3f  max=%.3f\n\n",
              label, s1, s3, s2))

  return(avg_rast)
}

capacity_rast  <- load_and_summarise(raster_paths$capacity,  "Capacity")
condition_rast <- load_and_summarise(raster_paths$condition, "Condition")

# Save overall rasters
cap_tif <- file.path(output_base,
                     paste0("biomass_overall_capacity_", depth_layer, ".tif"))
con_tif <- file.path(output_base,
                     paste0("biomass_overall_condition_", depth_layer, ".tif"))
writeRaster(capacity_rast,  cap_tif, overwrite = TRUE)
writeRaster(condition_rast, con_tif, overwrite = TRUE)
cat("  Saved: ", cap_tif, "\n", sep = "")
cat("  Saved: ", con_tif, "\n\n", sep = "")

# =============================================================================
# PART 2: Biomass Production Change — mean(U_geno − U_pheno)
# =============================================================================
# Direct measure of change: ΔU = U_geno − U_pheno per property
#   ΔU < 0 → phenosoil utility higher → Improved
#   ΔU ≈ 0 → no change
#   ΔU > 0 → genosoil utility higher → Degraded
# Averaged across pH, BD, AWC for overall biomass production change
# =============================================================================
cat("Computing biomass production change (mean \u0394U)...\n")

# Capacity functions (same as 11_3_soil_utility_map.R)
cap_fns <- list(
  pH  = function(x) exp(-(x - 6.5)^2 / 2),
  BD  = function(x) 1 / (1 + exp(10 * (x - 1.5))),
  AWC = function(x) 1 / (1 + exp(-1.0 * (x - 12)))
)

input_base <- file.path("Data", "data_out", "pedogenon_zonal_means")
delta_u_list <- list()

for (prop in c("pH", "BD", "AWC")) {
  prop_full <- switch(prop, pH = "pH", BD = "Bulk_Density", AWC = "AWC")
  geno_path  <- file.path(input_base, "Geno",
                           paste0(prop_full, "_geno_pedogenon_mean_",
                                  depth_layer, ".tif"))
  pheno_path <- file.path(input_base, "Pheno",
                           paste0(prop_full, "_pheno_pedogenon_mean_",
                                  depth_layer, ".tif"))

  cat("  ", prop, ": loading geno + pheno rasters...\n", sep = "")
  geno_r  <- rast(geno_path)
  pheno_r <- rast(pheno_path)

  fn <- cap_fns[[prop]]
  u_geno  <- app(geno_r,  fun = function(x) fn(x))
  u_pheno <- app(pheno_r, fun = function(x) fn(x))
  delta_u_list[[prop]] <- u_geno - u_pheno

  d_min  <- global(delta_u_list[[prop]], fun = "min",  na.rm = TRUE)$min
  d_max  <- global(delta_u_list[[prop]], fun = "max",  na.rm = TRUE)$max
  d_mean <- global(delta_u_list[[prop]], fun = "mean", na.rm = TRUE)$mean
  cat(sprintf("    \u0394U: min=%.3f  mean=%.3f  max=%.3f\n",
              d_min, d_mean, d_max))
}

# Mean ΔU across all properties
cat("  Averaging \u0394U across properties...\n")
delta_stack <- rast(delta_u_list)
change_rast <- app(delta_stack, fun = function(x) mean(x, na.rm = TRUE))

change_tif <- file.path(output_base,
                        paste0("biomass_change_", depth_layer, ".tif"))
writeRaster(change_rast, change_tif, overwrite = TRUE)

chg_s1 <- global(change_rast, fun = "min",  na.rm = TRUE)$min
chg_s2 <- global(change_rast, fun = "max",  na.rm = TRUE)$max
chg_s3 <- global(change_rast, fun = "mean", na.rm = TRUE)$mean
cat(sprintf("  Change: min=%.4f  mean=%.4f  max=%.4f\n\n",
            chg_s1, chg_s3, chg_s2))

# =============================================================================
# Summary
# =============================================================================
cat(paste(rep("=", 70), collapse = ""), "\n")
cat("DONE — Rasters saved to: ", output_base, "\n")
cat(paste(rep("=", 70), collapse = ""), "\n")
cat("  ", cap_tif, "\n")
cat("  ", con_tif, "\n")
cat("  ", change_tif, "\n")
cat("\nNext: source('R/11_3b2_biomass_production_plots.R') for maps & graphs\n")
cat(paste(rep("=", 70), collapse = ""), "\n")
